language: elm
elm-test: 0.19.0-rev6
node_js:
- '8'
before_script:
- bash build.sh
script: yarn test
deploy:
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: dist
  provider: pages
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: pkHxA/LjrdD5qOw/FucZn4ByAZr7n6kT6HW3QxjgBe7rc5zt8Dr+PyQhPWEFA+Y29XeudtvX3okhnA/3/t5QDj/LyP8RqEFhQKmXnK5CXy4dd8u+SX2IHAGK9sS+mIMAsdigtD7AcbrMRf3HcqHDvS5F2YzjD0YDB8HFjMT+yY9oq7OmTwFEgTbnaDk+GL8h84RQ5v7mLqGr6qEQ/7dTo8brKrJhYcUwgKhAWRA/0RBwqqf9D/QsyF2FPWjrVag+jtlBErYMT4A49W2SLR1LSFFBcjCkRYozbxzElVaSPfZf4dphWQ8Vdq/onfDHEWI0zNIhZhLYgITvS5Mcc8Dl4/fs1xYxCwiFTyQN2iIJjjgswTubiNUM06Re1fsxUjCFD0XFFl7j/sUMAUU+dHgOFY6pehx1YpYWdxvnb0yg9BirePKbw3WFUYw00ohdf24XbPiF/xNf8qDVmBKTWFBOibrlHx+gk4H2x2PCTvNRu+XKbVIn9hUyfcFOtiRqbIQpfytczJnwMy/TnfEQexXI3NHQ+ZQJ3Cv+jN1Q9b92oLIXs6JjquVnSKW+HzOU7hQKPQKgMmzhJG3Gd2kARMExAACu0G0ZgWvqX4AX/itceCbCF+J0y3lJedLfbFoIlv3E88AJTiZspnESctgRDzrTsMY3OOMCL9PnDvAPr14KdkM=
  - secure: n6ovK1iZLXGsVmL2gignNQYDSOvKZXDwhRFgjc237AienCXYqOwcI/sM9OrRkAY0F9wlDgatj/8SMHBIsFJToMB/ch+0pKJXQiN229Z1804cpimVV4oyGqNxYezQkG4YkK8kBMiSSeBEMkgAaIle53PV46/94LodvZUqA226USEUlhqABV6EGwcZ6YWrBaIZz1od17F0Mq/hFMTpu+AyO8VRDc+tmS+Y++JzG34rOuhezmEhqgsB38NxdvMAJw4CcCENVwt65BY23cJUo7XAW7TJ0NZyrPSlrXEXd/gvirQICnYTcCk9W3NOIkUwWGcUkxr7JQY2sz6i1NuRYiIz1Vyt2LGAKw52goiVZ9KdIi/WYOn1CTkRLMKYz2t+hCrrpcACNOidJIaHKx5sNeEkp/TI/fSkVrjRXEgJonNGJHQPbLlZZrLB7Th1jOTOQ/s9uYhyEqhAZ9o/Ay/ty4/gO5hBqEC6f608bac7aKpCZIWg0yBZbX7NmM+csOdzkEDS9v3fjnOQiU+a2fJr5LPQwIswW6t62TZxDXH2NGmxAkwExtE9o+Q/T+b23kWB+AKA8wSpTENmBPpWW8xwASGjh9QAmba+wR8uvQoGmJQRXERtpRXUya6jU2uUbNbzf1KQqQgzRvflOVhE7E+fvl0D6+2fyfL+WPnxQwrK9Iwj/4Q=
  - secure: Qju/PZPQI608z/4mYivt40Q0TO8GlJpkgEJ3MIH5eCj9AYXYZeq9Cod4jtZ4nIAxOdZ2so2lkZnFRBsE3vaS60wdYuFBuEoHxTrADRSzUVo8tPJlV0PAC0schA0w5h+9aR/7WidU439HgvTlD9WPuOb4W5QtWkzUp3Vzk0VfVXOqaQhor3uzNVurkdFQLDhjS/vusmKXVFVAz+OWGMhpHEytpmkhaWxkmyT4NFs7D17VqgWuz3Nh3U3ihYjM678+nyHHXR+ayLEfuadBSfludLwaPmSslp9eYxCCYjF40zGPWENlNESjanRpQY38mwAtumt06wCDPwdzAm96HYNPye/OyQlD+HYJ3JyaX/JDcDzVuJrWXXjEX+RbmP5DBg8x1EO1/JXtOhR1cz0HkGVdMXhkFI2XzgtFFTC/U0efKDDJDy09IMIfhnUp4m6AP3UKCNX5xuB1IakKsuloVQyhaT4hvLld7YHiKv/tTvrvtrR8W6ouIyVAFPN3Z81pGGJneutJmsPvgOZ/NU7WecrLX88IFDoa/NaopjvNrjgL9fcAQjFRDHIfHYTbPrGY8iDEHAjMm0Xl7KwDh6UICX0KlrwhCPz9IdIeH0IFhy16Q4bVyB09ktasN3fd1+DR38Yj1+IfEAzsw9GXRwp6vFMt25wxD0PV75Fkg+Iq4MCKQOM=
