language: elm
elm-test: 0.19.0-rev6
node_js:
- '8'
before_script:
- bash build.sh
script: yarn test
deploy:
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: dist
  provider: pages
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: pkHxA/LjrdD5qOw/FucZn4ByAZr7n6kT6HW3QxjgBe7rc5zt8Dr+PyQhPWEFA+Y29XeudtvX3okhnA/3/t5QDj/LyP8RqEFhQKmXnK5CXy4dd8u+SX2IHAGK9sS+mIMAsdigtD7AcbrMRf3HcqHDvS5F2YzjD0YDB8HFjMT+yY9oq7OmTwFEgTbnaDk+GL8h84RQ5v7mLqGr6qEQ/7dTo8brKrJhYcUwgKhAWRA/0RBwqqf9D/QsyF2FPWjrVag+jtlBErYMT4A49W2SLR1LSFFBcjCkRYozbxzElVaSPfZf4dphWQ8Vdq/onfDHEWI0zNIhZhLYgITvS5Mcc8Dl4/fs1xYxCwiFTyQN2iIJjjgswTubiNUM06Re1fsxUjCFD0XFFl7j/sUMAUU+dHgOFY6pehx1YpYWdxvnb0yg9BirePKbw3WFUYw00ohdf24XbPiF/xNf8qDVmBKTWFBOibrlHx+gk4H2x2PCTvNRu+XKbVIn9hUyfcFOtiRqbIQpfytczJnwMy/TnfEQexXI3NHQ+ZQJ3Cv+jN1Q9b92oLIXs6JjquVnSKW+HzOU7hQKPQKgMmzhJG3Gd2kARMExAACu0G0ZgWvqX4AX/itceCbCF+J0y3lJedLfbFoIlv3E88AJTiZspnESctgRDzrTsMY3OOMCL9PnDvAPr14KdkM=
  - secure: Qju/PZPQI608z/4mYivt40Q0TO8GlJpkgEJ3MIH5eCj9AYXYZeq9Cod4jtZ4nIAxOdZ2so2lkZnFRBsE3vaS60wdYuFBuEoHxTrADRSzUVo8tPJlV0PAC0schA0w5h+9aR/7WidU439HgvTlD9WPuOb4W5QtWkzUp3Vzk0VfVXOqaQhor3uzNVurkdFQLDhjS/vusmKXVFVAz+OWGMhpHEytpmkhaWxkmyT4NFs7D17VqgWuz3Nh3U3ihYjM678+nyHHXR+ayLEfuadBSfludLwaPmSslp9eYxCCYjF40zGPWENlNESjanRpQY38mwAtumt06wCDPwdzAm96HYNPye/OyQlD+HYJ3JyaX/JDcDzVuJrWXXjEX+RbmP5DBg8x1EO1/JXtOhR1cz0HkGVdMXhkFI2XzgtFFTC/U0efKDDJDy09IMIfhnUp4m6AP3UKCNX5xuB1IakKsuloVQyhaT4hvLld7YHiKv/tTvrvtrR8W6ouIyVAFPN3Z81pGGJneutJmsPvgOZ/NU7WecrLX88IFDoa/NaopjvNrjgL9fcAQjFRDHIfHYTbPrGY8iDEHAjMm0Xl7KwDh6UICX0KlrwhCPz9IdIeH0IFhy16Q4bVyB09ktasN3fd1+DR38Yj1+IfEAzsw9GXRwp6vFMt25wxD0PV75Fkg+Iq4MCKQOM=
  - secure: W1k96vqKwlOPr8R8Yh0cUMzdRt3CrQMqO8+KH7ySbs5HalPhdX7lX9o0ggZWh3Vu5b+ZBbU5Mvq1ZmElzxWskkheEuabV9U6gyZZQqoeb3gigxcRMqx5xlC22jsuIfW4hh/1scF5yOolJncHF9cRY2V2HM8/gGMP0oktaBzVsUQkUiEnVzt/6V297SRcOcu+JXtc3skabJP5OM0dcMnVAxEBgIEPqM8UFbrKqmTm6cEQMMZ2HD3TjhV1K+4CVUzC5Q6f93ZJ499SSb9zqMy1ffM7G+n64dlfnxwndYgPgPPaP2xpeYXRe2SC2u2oeScLSHTPC7BFn2z+lJyb2UqkfcVMMHpvQwax0xhWbO+gboaYnBRXSMc3vRGCD0hKclcy8L9aU52Neqn+1xCYJiIRwXD6mNVh+ezpIqwCiwO5jGBYzoSRitTcp1AeTnVUQF3anvgTnFaieOyUQzsjiG4T9b1jKG4iORELSx9RTI43df7ijdGuidFDmP4nEKMiXPVVa7jsiJuNUPNkdgtXMvIaPraxjzWPyclOtSMjX3h1nekYxRvP5JPHDh/s6pQ5wR2Wp5Q2+WB1rFdFx1yH6zIeHZtwZfNuxWdoLo6iX4rO0VVpQlMew9uNScuRps431DFZ+uLRSmFqN2bcYrdY3g4kK2HC8JXIXXGdGrS4+fNhwxA=
